logo: # add logo name
title: 王斌 (凤朝凰)
description: > # this means to ignore newlines until "baseurl:"
    这是我的个人博客网站，欢迎大家访问
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: 凤朝凰 # add banner title
banner-desc: 在浮躁的互联网浪潮中，做一个踏实的程序员。 # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: 王斌 <span>(凤朝凰)</span> # your name
about-author: 举家北漂的一枚小小程序员，不辞辛劳要技术深钻。不为富贵，只为了最初的梦想和糊口的饭。 # about author
about-work: 目前供职于HTC，在Android开发风风雨雨8年，从Framework做到Application，从C++做到Java。梦想有一天能够写出一个伟大的软件。 
email: wangbinds@qq.com # your email
phone: 要保密哟～～ # your pnone number
website: https://wangbinds.coding.me # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
#  - jekyll-paginate
#  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
